# -*- coding: utf-8 -*-
"""SBST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFcsl8knpkedvKzPYOb7tJ6MDqVAhjEM
"""

# Install RF-DETR with training dependencies, Roboflow SDK, and visualization tools
!pip install "rfdetr[train]>=1.4.0" roboflow supervision opencv-python matplotlib

"""Pull annotated set from Roboflow"""

from roboflow import Roboflow

# Initialize client using your private key from Roboflow settings
rf = Roboflow(api_key="79NT5SPJPI6rlNa8TdcZ")

# Connect to the SBST depot parking project
project = rf.workspace("hugh-chow").project("bus-parking-lot-number")
dataset = project.version(1).download("coco")

print(f"Dataset downloaded to: {dataset.location}")

"""Training the model. Best result at epoch = 14, EMA tracking saves the best weight"""

from rfdetr import RFDETRNano

# Initialize the lightweight Nano model
model = RFDETRNano()

# Train the model using the location from your downloaded dataset
# The system will automatically save the best weights via EMA tracking
model.train(
    dataset_dir=dataset.location,
    epochs=100,
    batch_size=4,          # Fits nicely inside the free T4 GPU
    grad_accum_steps=4     # 4x4 = 16 effective batch size
)

import cv2
import matplotlib.pyplot as plt
import glob
import supervision as sv
from rfdetr import RFDETRNano

# 1. Load the optimal trained checkpoint from the output directory
checkpoint_path = "/content/output/checkpoint_best_total.pth"
model = RFDETRNano(pretrain_weights=checkpoint_path)

# 2. Pick a test image from your held-out test dataset
test_images = glob.glob(f"{dataset.location}/test/*.jpg")
image_path = test_images[0]
frame_bgr = cv2.imread(image_path)
frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)

# 3. Predict bounding boxes
detections = model.predict(frame_rgb, threshold=0.5)

# 4. Annotate the frame using the Supervision library
box_annotator = sv.BoxAnnotator()
label_annotator = sv.LabelAnnotator()

labels = [f"Bay Marker {conf:.2f}" for conf in detections.confidence]
annotated_frame = box_annotator.annotate(scene=frame_bgr.copy(), detections=detections)
annotated_frame = label_annotator.annotate(scene=annotated_frame, detections=detections, labels=labels)

# 5. Display the result inline
annotated_rgb = cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(10, 6))
plt.imshow(annotated_rgb)
plt.axis("off")
plt.show()

from google.colab import files

# Trigger browser download for edge deployment
files.download("/content/output/checkpoint_best_total.pth")